- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

# - name: Reload nginx
#   service:
#     name: nginx
#     state: reloaded

- name: Copy nginx configuration for wordpress 
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx