- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install python3-libselinux (CentOS 8+)
  yum:
    name: python3-libselinux
    state: present

- name: Reload ansible_facts
  setup:

- name: Copy the EPEL repository definition 
  copy:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy:
    src: RPM-GPG-KEY-EPEL-9
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9

- name: Set up iptables rules
  copy:
    src: iptables-save
    dest: /etc/sysconfig/iptables
